package com.jabber.jrts.core.report;

import com.jabber.jrts.data.model.ModuleResult;
import com.google.gson.GsonBuilder;
import com.google.gson.Gson;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.*;

/**
 * Multi-format report engine supporting JSON, XML, CSV, Markdown, TXT, and HTML.
 */
@Service
public class ReportEngine {

    private final Gson gson = new GsonBuilder().setPrettyPrinting()
        .serializeNulls().create();

    public String generate(ModuleResult result, String format) {
        return switch (format.toLowerCase()) {
            case "json" -> generateJSON(result);
            case "xml" -> generateXML(result);
            case "csv" -> generateCSV(result);
            case "markdown", "md" -> generateMarkdown(result);
            case "txt" -> generateTXT(result);
            case "html" -> generateHTML(result);
            default -> generateJSON(result);
        };
    }

    private String generateJSON(ModuleResult result) {
        Map<String, Object> report = buildReportData(result);
        return gson.toJson(report);
    }

    private String generateXML(ModuleResult result) {
        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<JRTSReport>\n");
        xml.append("  <metadata>\n");
        xml.append("    <generator>JABBER Red Teaming Suite v1.0.0</generator>\n");
        xml.append("    <creator>Funbinet (dancan.tech)</creator>\n");
        xml.append("    <timestamp>").append(Instant.now()).append("</timestamp>\n");
        xml.append("    <taskId>").append(result.getTaskId()).append("</taskId>\n");
        xml.append("    <moduleId>").append(result.getModuleId()).append("</moduleId>\n");
        xml.append("    <status>").append(result.getStatus()).append("</status>\n");
        xml.append("  </metadata>\n");
        xml.append("  <findings count=\"").append(result.getFindings().size()).append("\">\n");
        for (Map<String, Object> finding : result.getFindings()) {
            xml.append("    <finding>\n");
            for (Map.Entry<String, Object> e : finding.entrySet()) {
                xml.append("      <").append(escapeXml(e.getKey())).append(">");
                xml.append(escapeXml(String.valueOf(e.getValue())));
                xml.append("</").append(escapeXml(e.getKey())).append(">\n");
            }
            xml.append("    </finding>\n");
        }
        xml.append("  </findings>\n");
        xml.append("  <log>\n");
        for (String line : result.getLogLines()) {
            xml.append("    <entry>").append(escapeXml(line)).append("</entry>\n");
        }
        xml.append("  </log>\n");
        xml.append("</JRTSReport>\n");
        return xml.toString();
    }

    private String generateCSV(ModuleResult result) {
        StringBuilder csv = new StringBuilder();
        csv.append("# JRTS Report - Generated by Funbinet (dancan.tech)\n");
        csv.append("# Task: ").append(result.getTaskId()).append("\n");
        csv.append("# Module: ").append(result.getModuleId()).append("\n\n");

        if (!result.getFindings().isEmpty()) {
            Set<String> headers = new LinkedHashSet<>();
            result.getFindings().forEach(f -> headers.addAll(f.keySet()));
            csv.append(String.join(",", headers)).append("\n");
            for (Map<String, Object> finding : result.getFindings()) {
                List<String> values = new ArrayList<>();
                for (String h : headers) {
                    String val = String.valueOf(finding.getOrDefault(h, ""));
                    values.add("\"" + val.replace("\"", "\"\"") + "\"");
                }
                csv.append(String.join(",", values)).append("\n");
            }
        }
        return csv.toString();
    }

    private String generateMarkdown(ModuleResult result) {
        StringBuilder md = new StringBuilder();
        md.append("# JRTS Operation Report\n\n");
        md.append("**Generator**: JABBER Red Teaming Suite v1.0.0\n");
        md.append("**Created by**: Funbinet (dancan.tech)\n");
        md.append("**Timestamp**: ").append(Instant.now()).append("\n\n");
        md.append("## Task Information\n\n");
        md.append("| Field | Value |\n|---|---|\n");
        md.append("| Task ID | `").append(result.getTaskId()).append("` |\n");
        md.append("| Module | `").append(result.getModuleId()).append("` |\n");
        md.append("| Status | **").append(result.getStatus()).append("** |\n");
        md.append("| Start Time | ").append(result.getStartTime()).append(" |\n");
        md.append("| End Time | ").append(result.getEndTime()).append(" |\n\n");

        if (!result.getFindings().isEmpty()) {
            md.append("## Findings (").append(result.getFindings().size()).append(")\n\n");
            for (int i = 0; i < result.getFindings().size(); i++) {
                md.append("### Finding ").append(i + 1).append("\n\n");
                Map<String, Object> finding = result.getFindings().get(i);
                for (Map.Entry<String, Object> e : finding.entrySet()) {
                    md.append("- **").append(e.getKey()).append("**: ").append(e.getValue()).append("\n");
                }
                md.append("\n");
            }
        }

        md.append("## Execution Log\n\n```\n");
        result.getLogLines().forEach(line -> md.append(line).append("\n"));
        md.append("```\n");

        return md.toString();
    }

    private String generateTXT(ModuleResult result) {
        StringBuilder txt = new StringBuilder();
        txt.append("===============================================================\n");
        txt.append("  JRTS - JABBER Red Teaming Suite - Operation Report\n");
        txt.append("  Created by Funbinet (dancan.tech)\n");
        txt.append("===============================================================\n\n");
        txt.append("Task ID:    ").append(result.getTaskId()).append("\n");
        txt.append("Module:     ").append(result.getModuleId()).append("\n");
        txt.append("Status:     ").append(result.getStatus()).append("\n");
        txt.append("Started:    ").append(result.getStartTime()).append("\n");
        txt.append("Completed:  ").append(result.getEndTime()).append("\n\n");

        txt.append("--- FINDINGS ---\n\n");
        for (Map<String, Object> finding : result.getFindings()) {
            for (Map.Entry<String, Object> e : finding.entrySet()) {
                txt.append("  ").append(e.getKey()).append(": ").append(e.getValue()).append("\n");
            }
            txt.append("\n");
        }

        txt.append("--- EXECUTION LOG ---\n\n");
        result.getLogLines().forEach(line -> txt.append("  ").append(line).append("\n"));

        return txt.toString();
    }

    private String generateHTML(ModuleResult result) {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<title>JRTS Report - ").append(result.getModuleId()).append("</title>\n");
        html.append("<style>\n");
        html.append("  body { font-family: 'Inter', sans-serif; background: #0d1117; color: #c9d1d9; padding: 2rem; }\n");
        html.append("  h1 { color: #ff4444; border-bottom: 2px solid #21262d; padding-bottom: 0.5rem; }\n");
        html.append("  h2 { color: #58a6ff; }\n");
        html.append("  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }\n");
        html.append("  th, td { border: 1px solid #30363d; padding: 0.5rem; text-align: left; }\n");
        html.append("  th { background: #161b22; color: #ff4444; }\n");
        html.append("  .log { background: #0d1117; border: 1px solid #30363d; padding: 1rem; ");
        html.append("font-family: monospace; color: #00ff41; white-space: pre; overflow-x: auto; }\n");
        html.append("  .meta { color: #8b949e; font-size: 0.9rem; }\n");
        html.append("  .badge { padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; }\n");
        html.append("  .badge-critical { background: #f8514940; color: #f85149; }\n");
        html.append("  .badge-completed { background: #23863640; color: #3fb950; }\n");
        html.append("</style>\n</head>\n<body>\n");
        html.append("<h1>JRTS Operation Report</h1>\n");
        html.append("<p class=\"meta\">Generated by JABBER Red Teaming Suite v1.0.0 | Created by Funbinet (dancan.tech)</p>\n\n");

        html.append("<h2>Task Details</h2>\n<table>\n");
        html.append("<tr><th>Field</th><th>Value</th></tr>\n");
        html.append("<tr><td>Task ID</td><td><code>").append(result.getTaskId()).append("</code></td></tr>\n");
        html.append("<tr><td>Module</td><td>").append(result.getModuleId()).append("</td></tr>\n");
        html.append("<tr><td>Status</td><td><span class=\"badge badge-completed\">").append(result.getStatus()).append("</span></td></tr>\n");
        html.append("<tr><td>Start</td><td>").append(result.getStartTime()).append("</td></tr>\n");
        html.append("<tr><td>End</td><td>").append(result.getEndTime()).append("</td></tr>\n");
        html.append("</table>\n\n");

        if (!result.getFindings().isEmpty()) {
            html.append("<h2>Findings (").append(result.getFindings().size()).append(")</h2>\n");
            html.append("<table>\n");
            Set<String> headers = new LinkedHashSet<>();
            result.getFindings().forEach(f -> headers.addAll(f.keySet()));
            html.append("<tr>");
            headers.forEach(h -> html.append("<th>").append(escapeHtml(h)).append("</th>"));
            html.append("</tr>\n");
            for (Map<String, Object> finding : result.getFindings()) {
                html.append("<tr>");
                for (String h : headers) {
                    html.append("<td>").append(escapeHtml(String.valueOf(finding.getOrDefault(h, "")))).append("</td>");
                }
                html.append("</tr>\n");
            }
            html.append("</table>\n");
        }

        html.append("\n<h2>Execution Log</h2>\n<div class=\"log\">");
        result.getLogLines().forEach(line -> html.append(escapeHtml(line)).append("\n"));
        html.append("</div>\n\n</body>\n</html>");

        return html.toString();
    }

    private Map<String, Object> buildReportData(ModuleResult result) {
        Map<String, Object> report = new LinkedHashMap<>();
        report.put("generator", "JABBER Red Teaming Suite v1.0.0");
        report.put("creator", "Funbinet (dancan.tech)");
        report.put("timestamp", Instant.now().toString());
        report.put("task", Map.of(
            "taskId", result.getTaskId(),
            "moduleId", result.getModuleId(),
            "status", result.getStatus(),
            "startTime", String.valueOf(result.getStartTime()),
            "endTime", String.valueOf(result.getEndTime())
        ));
        report.put("output", result.getOutput());
        report.put("findings", result.getFindings());
        report.put("log", result.getLogLines());
        return report;
    }

    private String escapeXml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&apos;");
    }

    private String escapeHtml(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
